all:
  hosts:
    master:
      ansible_user: master
      ansible_host: 192.168.101.22
      ip: 192.168.101.22
      access_ip: 192.168.101.22
    cloud:
      ansible_user: cloud
      ansible_host: 192.168.101.15
      ip: 192.168.101.15
      access_ip: 192.168.101.15
    edge1:
      ansible_user: edge1
      ansible_host: 192.168.101.16
      ip: 192.168.101.16
      access_ip: 192.168.101.16
    edge2:
      ansible_user: edge2
      ansible_host: 192.168.101.17
      ip: 192.168.101.17
      access_ip: 192.168.101.17
    fog1:
      ansible_user: fog1
      ansible_host: 192.168.101.18
      ip: 192.168.101.18
      access_ip: 192.168.101.18
    fog2:
      ansible_user: fog2
      ansible_host: 192.168.101.19
      ip: 192.168.101.19
      access_ip: 192.168.101.19
    fog3:
      ansible_user: fog3
      ansible_host: 192.168.101.20
      ip: 192.168.101.20
      access_ip: 192.168.101.20
    fog4:
      ansible_user: fog4
      ansible_host: 192.168.101.21
      ip: 192.168.101.21
      access_ip: 192.168.101.21
  children:
    kube_control_plane:
      hosts:
        master:
    kube_node:
      hosts:
        cloud:
        edge1:
        edge2:
        fog1:
        fog2:
        fog3:
        fog4:
    etcd:
      hosts:
        master:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
